//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam_Library_Manager.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Games {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Games() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Steam_Library_Manager.Languages.Games", typeof(Games).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have canceled the process. Would you like to remove moved files from target library?.
        /// </summary>
        internal static string message_canceledProcess {
            get {
                return ResourceManager.GetString("message_canceledProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}/{1}] Compressed: {2}.
        /// </summary>
        internal static string message_compressStatus {
            get {
                return ResourceManager.GetString("message_compressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved files removed..
        /// </summary>
        internal static string message_filesRemoved {
            get {
                return ResourceManager.GetString("message_filesRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}/{1}] Copied: {2}.
        /// </summary>
        internal static string message_processStatus {
            get {
                return ResourceManager.GetString("message_processStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}/{1}] File couldn&apos;t verified: {2}.
        /// </summary>
        internal static string messageError_fileNotVerified {
            get {
                return ResourceManager.GetString("messageError_fileNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while updating game list!{1}{1}{1}{0}.
        /// </summary>
        internal static string messageError_unknownErrorWhileUpdatingGames {
            get {
                return ResourceManager.GetString("messageError_unknownErrorWhileUpdatingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove moved files?.
        /// </summary>
        internal static string messageTitle_canceledProcess {
            get {
                return ResourceManager.GetString("messageTitle_canceledProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string source_Games {
            get {
                return ResourceManager.GetString("source_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games - #updateGameList.
        /// </summary>
        internal static string source_updateGameList {
            get {
                return ResourceManager.GetString("source_updateGameList", resourceCulture);
            }
        }
    }
}
