//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam_Library_Manager.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SteamLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SteamLibrary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Steam_Library_Manager.Languages.SteamLibrary", typeof(SteamLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{2}] {0} ({1}).
        /// </summary>
        internal static string label_libraryName {
            get {
                return ResourceManager.GetString("label_libraryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Steam Library created, Please Restart Steam to see it in action..
        /// </summary>
        internal static string message_newSteamLibraryCreated {
            get {
                return ResourceManager.GetString("message_newSteamLibraryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new library.
        /// </summary>
        internal static string messageError_failedToCreateNewLibrary {
            get {
                return ResourceManager.GetString("messageError_failedToCreateNewLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library exists in the selected path! Are you trying to bug yourself?!.
        /// </summary>
        internal static string messageError_libraryExists {
            get {
                return ResourceManager.GetString("messageError_libraryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries can not be created in root.
        /// </summary>
        internal static string messageError_noLibraryInRoot {
            get {
                return ResourceManager.GetString("messageError_noLibraryInRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup library couldn&apos;t be found: {0}{1}{1} Would you like to change path?.
        /// </summary>
        internal static string messageWarning_updateWrongBackupDir {
            get {
                return ResourceManager.GetString("messageWarning_updateWrongBackupDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup directory {0} not found.
        /// </summary>
        internal static string messageWarningTitle_updateWrongBackupDir {
            get {
                return ResourceManager.GetString("messageWarningTitle_updateWrongBackupDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries.
        /// </summary>
        internal static string source_Libraries {
            get {
                return ResourceManager.GetString("source_Libraries", resourceCulture);
            }
        }
    }
}
