//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam_Library_Manager.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Updater {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Updater() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Steam_Library_Manager.Languages.Updater", typeof(Updater).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string label_latestVersionText {
            get {
                return ResourceManager.GetString("label_latestVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using Latest Version of SLM..
        /// </summary>
        internal static string label_usingLatestVersion {
            get {
                return ResourceManager.GetString("label_usingLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your SLM version is OUT OF DATE, please update..
        /// </summary>
        internal static string label_versionResult_OutOfDate {
            get {
                return ResourceManager.GetString("label_versionResult_OutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT IS NOT SUGGESTED TO SKIP AN IMPORTANT UPGRADE, YOU MAY LOSE DATA WHILE MOVING A GAME, BE AWARE!.
        /// </summary>
        internal static string message_notSuggestedToSkip {
            get {
                return ResourceManager.GetString("message_notSuggestedToSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLM Updated.
        /// </summary>
        internal static string message_slmUpdated {
            get {
                return ResourceManager.GetString("message_slmUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an update available for SLM. Would you like to download it?{2}{2}Clicking \&quot;YES\&quot; will download latest version of SLM close current instance of SLM and update{2}{2}Latest Version: {0} - Importance: {1}.
        /// </summary>
        internal static string message_updateAvailable {
            get {
                return ResourceManager.GetString("message_updateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU SHOULD NOT SKIP AN IMPORTANT UPDATE.
        /// </summary>
        internal static string messageTitle_notSuggestedToSkip {
            get {
                return ResourceManager.GetString("messageTitle_notSuggestedToSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLM Update Checker.
        /// </summary>
        internal static string messageTitle_updateAvailable {
            get {
                return ResourceManager.GetString("messageTitle_updateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updater.
        /// </summary>
        internal static string source_Updater {
            get {
                return ResourceManager.GetString("source_Updater", resourceCulture);
            }
        }
    }
}
