//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam_Library_Manager.Languages.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class moveLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal moveLibrary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Steam_Library_Manager.Languages.Forms.moveLibrary", typeof(moveLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - SLM - Move Library.
        /// </summary>
        internal static string form_Title {
            get {
                return ResourceManager.GetString("form_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details: {0}.
        /// </summary>
        internal static string groupBox_selectedLibraryText {
            get {
                return ResourceManager.GetString("groupBox_selectedLibraryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target: {0}.
        /// </summary>
        internal static string groupBox_targetLibraryText {
            get {
                return ResourceManager.GetString("groupBox_targetLibraryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files: {0} / {1}.
        /// </summary>
        internal static string label_progressInformationText {
            get {
                return ResourceManager.GetString("label_progressInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed!.
        /// </summary>
        internal static string message_Completed {
            get {
                return ResourceManager.GetString("message_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Library?.
        /// </summary>
        internal static string message_isBackupLibrary {
            get {
                return ResourceManager.GetString("message_isBackupLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library exists at selected path.
        /// </summary>
        internal static string messageError_libraryExists {
            get {
                return ResourceManager.GetString("messageError_libraryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam libraries can not be created in root.
        /// </summary>
        internal static string messageError_noLibraryInRoot {
            get {
                return ResourceManager.GetString("messageError_noLibraryInRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup?.
        /// </summary>
        internal static string messageTitle_isBackupLibrary {
            get {
                return ResourceManager.GetString("messageTitle_isBackupLibrary", resourceCulture);
            }
        }
    }
}
