//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam_Library_Manager.Languages.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class moveGame {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal moveGame() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Steam_Library_Manager.Languages.Forms.moveGame", typeof(moveGame).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string button_copyText_Backup {
            get {
                return ResourceManager.GetString("button_copyText_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed!.
        /// </summary>
        internal static string button_copyText_Completed {
            get {
                return ResourceManager.GetString("button_copyText_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string button_copyText_Restore {
            get {
                return ResourceManager.GetString("button_copyText_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - SLM.
        /// </summary>
        internal static string form_Text {
            get {
                return ResourceManager.GetString("form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free space is not enough! Needed Free Space: {0} Available: {1}.
        /// </summary>
        internal static string logError_freeSpaceIsNotEnough {
            get {
                return ResourceManager.GetString("logError_freeSpaceIsNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while compressing game files.
        /// </summary>
        internal static string logError_unknownErrorWhileCompressing {
            get {
                return ResourceManager.GetString("logError_unknownErrorWhileCompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while copying game archive.
        /// </summary>
        internal static string logError_unknownErrorWhileCopyingArchive {
            get {
                return ResourceManager.GetString("logError_unknownErrorWhileCopyingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while copying game files.
        /// </summary>
        internal static string logError_unknownErrorWhileCopyingFiles {
            get {
                return ResourceManager.GetString("logError_unknownErrorWhileCopyingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while de-compressing archive.
        /// </summary>
        internal static string logError_unknownErrorWhileDecompressing {
            get {
                return ResourceManager.GetString("logError_unknownErrorWhileDecompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while removing old files.
        /// </summary>
        internal static string logError_unknownErrorWhileRemovingFiles {
            get {
                return ResourceManager.GetString("logError_unknownErrorWhileRemovingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File list generated. Files will be moved: {0}.
        /// </summary>
        internal static string logMessage_fileListGenerated {
            get {
                return ResourceManager.GetString("logMessage_fileListGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while SLM generates file list..
        /// </summary>
        internal static string logMessage_generatingFileList {
            get {
                return ResourceManager.GetString("logMessage_generatingFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process has been completed, you may close this window now..
        /// </summary>
        internal static string logMessage_processCompleted {
            get {
                return ResourceManager.GetString("logMessage_processCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time elapsed: {0}.
        /// </summary>
        internal static string logMessage_timeElapsed {
            get {
                return ResourceManager.GetString("logMessage_timeElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User canceled process..
        /// </summary>
        internal static string logMessage_userCanceledProcess {
            get {
                return ResourceManager.GetString("logMessage_userCanceledProcess", resourceCulture);
            }
        }
    }
}
