//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam_Library_Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Steam_Library_Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{AppName}] An error happened while moving game files. Time Elapsed: {ElapsedTime}.
        /// </summary>
        internal static string AnyError_ElapsedTime {
            get {
                return ResourceManager.GetString("AnyError_ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{AppName}] An error happened while moving game files.
        ///
        ///{ExceptionMessage}
        ///
        ///Would you like to remove files that already moved from target library?.
        /// </summary>
        internal static string AnyException_RemoveFiles {
            get {
                return ResourceManager.GetString("AnyException_RemoveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Updater.
        /// </summary>
        internal static string AutoUpdater {
            get {
                return ResourceManager.GetString("AutoUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{AppName}] An error related to file system is happened while compressing files.
        ///
        ///Error: {ExceptionMessage}.
        ///
        ///Would you like to remove archive file that is generated by SLM?.
        /// </summary>
        internal static string CompressArchive_FileNotFoundEx {
            get {
                return ResourceManager.GetString("CompressArchive_FileNotFoundEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap compressedLibraryIcon {
            get {
                object obj = ResourceManager.GetObject("compressedLibraryIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Library Manager.
        /// </summary>
        internal static string CreateLibrary_Exists {
            get {
                return ResourceManager.GetString("CreateLibrary_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library already exists at {LibraryPath}.
        /// </summary>
        internal static string CreateLibrary_ExistsMessage {
            get {
                return ResourceManager.GetString("CreateLibrary_ExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Library Manager.
        /// </summary>
        internal static string CreateLibrary_RootError {
            get {
                return ResourceManager.GetString("CreateLibrary_RootError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries can not be created at root.
        /// </summary>
        internal static string CreateLibrary_RootErrorMessage {
            get {
                return ResourceManager.GetString("CreateLibrary_RootErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Library Manager.
        /// </summary>
        internal static string CreateLibraryDialog {
            get {
                return ResourceManager.GetString("CreateLibraryDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Library type you want to create in folder:
        ///{LibraryPath}.
        /// </summary>
        internal static string CreateLibraryDialogMessage {
            get {
                return ResourceManager.GetString("CreateLibraryDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Steam library created.
        /// </summary>
        internal static string CreateSteamLibrary_Created {
            get {
                return ResourceManager.GetString("CreateSteamLibrary_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy Steam.dll.
        /// </summary>
        internal static string CreateSteamLibrary_UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("CreateSteamLibrary_UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error related to file system is happened while creating a new library at: {NewLibraryPath}
        ///
        ///Error: {ExceptionMessage}.
        ///
        ///The error is related to file system permissions. Try running SLM as administrator or take the target folder permissions for your user..
        /// </summary>
        internal static string CreateSteamLibrary_UnauthorizedAccessExceptionMessage {
            get {
                return ResourceManager.GetString("CreateSteamLibrary_UnauthorizedAccessExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy Steam.dll into new library directory. Permission error, maybe?.
        /// </summary>
        internal static string CreateSteamLibrary_UnknownError {
            get {
                return ResourceManager.GetString("CreateSteamLibrary_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete library without moving games.
        /// </summary>
        internal static string DeleteLibraryWithoutMovingGames {
            get {
                return ResourceManager.GetString("DeleteLibraryWithoutMovingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Library Manager.
        /// </summary>
        internal static string DeleteMainSteamLibrary {
            get {
                return ResourceManager.GetString("DeleteMainSteamLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t remove the main library of Steam, can you? Never tested tbh. TODO: TEST!.
        /// </summary>
        internal static string DeleteMainSteamLibraryMessage {
            get {
                return ResourceManager.GetString("DeleteMainSteamLibraryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Library Manager.
        /// </summary>
        internal static string DeleteSteamLibrary {
            get {
                return ResourceManager.GetString("DeleteSteamLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All game files in library successfully removed as requested.
        ///
        ///Library: {LibraryFullPath}.
        /// </summary>
        internal static string DeleteSteamLibraryMessage {
            get {
                return ResourceManager.GetString("DeleteSteamLibraryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectoryNotFoundException.
        /// </summary>
        internal static string DirectoryNotFoundException {
            get {
                return ResourceManager.GetString("DirectoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{FolderfullPath}] Folder couldn&apos;t be created/not found. Running SLM as Administrator might help.
        ///
        ///Error: {ExceptionMessage}.
        /// </summary>
        internal static string DirectoryNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("DirectoryNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Enums_AppID {
            get {
                return ResourceManager.GetString("Enums_AppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size in archive.
        /// </summary>
        internal static string Enums_ArchiveFileSize {
            get {
                return ResourceManager.GetString("Enums_ArchiveFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive size.
        /// </summary>
        internal static string Enums_ArchiveSize {
            get {
                return ResourceManager.GetString("Enums_ArchiveSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup type.
        /// </summary>
        internal static string Enums_BackupType {
            get {
                return ResourceManager.GetString("Enums_BackupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress.
        /// </summary>
        internal static string Enums_Compress {
            get {
                return ResourceManager.GetString("Enums_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Enums_Copy {
            get {
                return ResourceManager.GetString("Enums_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Theme.
        /// </summary>
        internal static string Enums_Custom {
            get {
                return ResourceManager.GetString("Enums_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        internal static string Enums_Dark {
            get {
                return ResourceManager.GetString("Enums_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Enums_Delete {
            get {
                return ResourceManager.GetString("Enums_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid View.
        /// </summary>
        internal static string Enums_GridView {
            get {
                return ResourceManager.GetString("Enums_GridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last play.
        /// </summary>
        internal static string Enums_LastPlayed {
            get {
                return ResourceManager.GetString("Enums_LastPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update.
        /// </summary>
        internal static string Enums_LastUpdate {
            get {
                return ResourceManager.GetString("Enums_LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        internal static string Enums_Light {
            get {
                return ResourceManager.GetString("Enums_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List View.
        /// </summary>
        internal static string Enums_ListView {
            get {
                return ResourceManager.GetString("Enums_ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Enums_Name {
            get {
                return ResourceManager.GetString("Enums_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size on disk.
        /// </summary>
        internal static string Enums_SizeOnDisk {
            get {
                return ResourceManager.GetString("Enums_SizeOnDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{AppName}] File list populated, total files to move: {FileCount} - total size to move: {TotalFileSize}.
        /// </summary>
        internal static string FileListPopulated {
            get {
                return ResourceManager.GetString("FileListPopulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{AppName}] File copied: {NewFileName}.
        /// </summary>
        internal static string FileMoved {
            get {
                return ResourceManager.GetString("FileMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{AppName}] An error releated to file permissions happened during file movement. Running SLM as Administrator might help.
        ///
        ///Error: {ExceptionMessage}.
        ///
        ///Would you like to remove files that already moved from target library?.
        /// </summary>
        internal static string FilePermissionRelatedError_DeleteFiles {
            get {
                return ResourceManager.GetString("FilePermissionRelatedError_DeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{AppName}] An error related to file system is happened while moving files. Error: {ExceptionMessage}.
        /// </summary>
        internal static string FileSystemRelatedError {
            get {
                return ResourceManager.GetString("FileSystemRelatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{AppName}] An error releated to file system is happened while moving files.
        ///
        ///Error: {ExceptionMessage}
        ///
        ///Would you like to remove files that already moved from target library?.
        /// </summary>
        internal static string FileSystemRelatedError_DeleteMovedFiles {
            get {
                return ResourceManager.GetString("FileSystemRelatedError_DeleteMovedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FontAwesome {
            get {
                object obj = ResourceManager.GetObject("FontAwesome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated on: {0}.
        /// </summary>
        internal static string Forms_AppView_LastUpdate {
            get {
                return ResourceManager.GetString("Forms_AppView_LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Forms_Cancel {
            get {
                return ResourceManager.GetString("Forms_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed.
        /// </summary>
        internal static string Forms_Compressed {
            get {
                return ResourceManager.GetString("Forms_Compressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing junk files as you have requested..
        /// </summary>
        internal static string Forms_LibraryCleaner_Delete {
            get {
                return ResourceManager.GetString("Forms_LibraryCleaner_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string Forms_LibraryCleaner_DeleteAll {
            get {
                return ResourceManager.GetString("Forms_LibraryCleaner_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected Folder(s).
        /// </summary>
        internal static string Forms_LibraryCleaner_DeleteSelectedFolders {
            get {
                return ResourceManager.GetString("Forms_LibraryCleaner_DeleteSelectedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There might be saved games in these folders?!.
        /// </summary>
        internal static string Forms_LibraryCleaner_DeleteWarning {
            get {
                return ResourceManager.GetString("Forms_LibraryCleaner_DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Games may be located within these folders, are you sure you want to remove them?.
        /// </summary>
        internal static string Forms_LibraryCleaner_DeleteWarningMessage {
            get {
                return ResourceManager.GetString("Forms_LibraryCleaner_DeleteWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing old directory:
        ///
        ///{DirectoryFullPath}.
        /// </summary>
        internal static string Forms_LibraryCleaner_DeletingDirectory {
            get {
                return ResourceManager.GetString("Forms_LibraryCleaner_DeletingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Write Time: {0}.
        /// </summary>
        internal static string Forms_LibraryCleaner_LastWriteTime {
            get {
                return ResourceManager.GetString("Forms_LibraryCleaner_LastWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move All.
        /// </summary>
        internal static string Forms_LibraryCleaner_MoveAll {
            get {
                return ResourceManager.GetString("Forms_LibraryCleaner_MoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving file:
        ///
        ///{FileFullName}.
        /// </summary>
        internal static string Forms_LibraryCleaner_MovingFile {
            get {
                return ResourceManager.GetString("Forms_LibraryCleaner_MovingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving junk files as you have requested..
        /// </summary>
        internal static string Forms_LibraryCleaner_MovingFiles {
            get {
                return ResourceManager.GetString("Forms_LibraryCleaner_MovingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Explorer.
        /// </summary>
        internal static string Forms_LibraryCleaner_Open {
            get {
                return ResourceManager.GetString("Forms_LibraryCleaner_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh List.
        /// </summary>
        internal static string Forms_LibraryCleaner_RefreshList {
            get {
                return ResourceManager.GetString("Forms_LibraryCleaner_RefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root path selected?.
        /// </summary>
        internal static string Forms_LibraryCleaner_RootPathSelected {
            get {
                return ResourceManager.GetString("Forms_LibraryCleaner_RootPathSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you like to move junks to root of disk?.
        /// </summary>
        internal static string Forms_LibraryCleaner_RootPathSelectedMessage {
            get {
                return ResourceManager.GetString("Forms_LibraryCleaner_RootPathSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App(s): {0}.
        /// </summary>
        internal static string Forms_LibraryView_AppCount {
            get {
                return ResourceManager.GetString("Forms_LibraryView_AppCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Library.
        /// </summary>
        internal static string Forms_LibraryView_CloseLibrary {
            get {
                return ResourceManager.GetString("Forms_LibraryView_CloseLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the selected library from SLM without touching files inside..
        /// </summary>
        internal static string Forms_LibraryView_CloseLibraryText {
            get {
                return ResourceManager.GetString("Forms_LibraryView_CloseLibraryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only available for (non-main) Origin and SLM libraries..
        /// </summary>
        internal static string Forms_LibraryView_CloseLibraryText2 {
            get {
                return ResourceManager.GetString("Forms_LibraryView_CloseLibraryText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Library.
        /// </summary>
        internal static string Forms_LibraryView_CreateLibrary {
            get {
                return ResourceManager.GetString("Forms_LibraryView_CreateLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Steam, Origin or SLM library at selected directory..
        /// </summary>
        internal static string Forms_LibraryView_CreateLibraryText {
            get {
                return ResourceManager.GetString("Forms_LibraryView_CreateLibraryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Forms_LibraryView_Offline {
            get {
                return ResourceManager.GetString("Forms_LibraryView_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Library.
        /// </summary>
        internal static string Forms_LibraryView_RefreshLibrary {
            get {
                return ResourceManager.GetString("Forms_LibraryView_RefreshLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshes the current status of selected library..
        /// </summary>
        internal static string Forms_LibraryView_RefreshLibraryText {
            get {
                return ResourceManager.GetString("Forms_LibraryView_RefreshLibraryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        internal static string Forms_Main_Discord {
            get {
                return ResourceManager.GetString("Forms_Main_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string Forms_Main_Donate {
            get {
                return ResourceManager.GetString("Forms_Main_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in selected library.
        /// </summary>
        internal static string Forms_Main_SearchInLibrary {
            get {
                return ResourceManager.GetString("Forms_Main_SearchInLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion Form.
        /// </summary>
        internal static string Forms_Main_SuggestionForm {
            get {
                return ResourceManager.GetString("Forms_Main_SuggestionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string Forms_Main_TabHeader_Library {
            get {
                return ResourceManager.GetString("Forms_Main_TabHeader_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Cleaner.
        /// </summary>
        internal static string Forms_Main_TabHeader_LibraryCleaner {
            get {
                return ResourceManager.GetString("Forms_Main_TabHeader_LibraryCleaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Forms_Main_TabHeader_Settings {
            get {
                return ResourceManager.GetString("Forms_Main_TabHeader_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Manager.
        /// </summary>
        internal static string Forms_Main_TabHeader_TaskManager {
            get {
                return ResourceManager.GetString("Forms_Main_TabHeader_TaskManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        internal static string Forms_Main_Translate {
            get {
                return ResourceManager.GetString("Forms_Main_Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        internal static string Forms_Origin {
            get {
                return ResourceManager.GetString("Forms_Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Forms_Quit {
            get {
                return ResourceManager.GetString("Forms_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit application?.
        /// </summary>
        internal static string Forms_QuitSLM {
            get {
                return ResourceManager.GetString("Forms_QuitSLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are active tasked jobs available in Task Manager. Are you sure you want to quit SLM? This might result in a data loss..
        /// </summary>
        internal static string Forms_QuitSLMMessage {
            get {
                return ResourceManager.GetString("Forms_QuitSLMMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Logging (Requires restart).
        /// </summary>
        internal static string Forms_Settings_AdvancedLogging {
            get {
                return ResourceManager.GetString("Forms_Settings_AdvancedLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string Forms_Settings_Background {
            get {
                return ResourceManager.GetString("Forms_Settings_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button BG.
        /// </summary>
        internal static string Forms_Settings_ButtonBG {
            get {
                return ResourceManager.GetString("Forms_Settings_ButtonBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Click.
        /// </summary>
        internal static string Forms_Settings_ButtonClick {
            get {
                return ResourceManager.GetString("Forms_Settings_ButtonClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Hover.
        /// </summary>
        internal static string Forms_Settings_ButtonHover {
            get {
                return ResourceManager.GetString("Forms_Settings_ButtonHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation method for archive size.
        /// </summary>
        internal static string Forms_Settings_CalculationMethodForArchiveSize {
            get {
                return ResourceManager.GetString("Forms_Settings_CalculationMethodForArchiveSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string Forms_Settings_CheckForUpdates {
            get {
                return ResourceManager.GetString("Forms_Settings_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates on Startup.
        /// </summary>
        internal static string Forms_Settings_CheckForUpdatesOnStartup {
            get {
                return ResourceManager.GetString("Forms_Settings_CheckForUpdatesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear header image cache.
        /// </summary>
        internal static string Forms_Settings_ClearHeaderİmageCache {
            get {
                return ResourceManager.GetString("Forms_Settings_ClearHeaderİmageCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress.
        /// </summary>
        internal static string Forms_Settings_Compress {
            get {
                return ResourceManager.GetString("Forms_Settings_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress Files.
        /// </summary>
        internal static string Forms_Settings_CompressFiles {
            get {
                return ResourceManager.GetString("Forms_Settings_CompressFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression Type.
        /// </summary>
        internal static string Forms_Settings_CompressionType {
            get {
                return ResourceManager.GetString("Forms_Settings_CompressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Menu.
        /// </summary>
        internal static string Forms_Settings_ContextMenu {
            get {
                return ResourceManager.GetString("Forms_Settings_ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control BG.
        /// </summary>
        internal static string Forms_Settings_ControlBG {
            get {
                return ResourceManager.GetString("Forms_Settings_ControlBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Theme.
        /// </summary>
        internal static string Forms_Settings_CustomTheme {
            get {
                return ResourceManager.GetString("Forms_Settings_CustomTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do NOT Compress.
        /// </summary>
        internal static string Forms_Settings_DoNOTCompress {
            get {
                return ResourceManager.GetString("Forms_Settings_DoNOTCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do NOT Remove.
        /// </summary>
        internal static string Forms_Settings_DoNOTRemove {
            get {
                return ResourceManager.GetString("Forms_Settings_DoNOTRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game listing method.
        /// </summary>
        internal static string Forms_Settings_GameListMethod {
            get {
                return ResourceManager.GetString("Forms_Settings_GameListMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string Forms_Settings_GeneralSettings {
            get {
                return ResourceManager.GetString("Forms_Settings_GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrayBrush1.
        /// </summary>
        internal static string Forms_Settings_GrayBrush1 {
            get {
                return ResourceManager.GetString("Forms_Settings_GrayBrush1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrayBrush2.
        /// </summary>
        internal static string Forms_Settings_GrayBrush2 {
            get {
                return ResourceManager.GetString("Forms_Settings_GrayBrush2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Library Manager.
        /// </summary>
        internal static string Forms_Settings_HeaderImageCache {
            get {
                return ResourceManager.GetString("Forms_Settings_HeaderImageCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Image Cache cleared..
        /// </summary>
        internal static string Forms_Settings_HeaderImageCacheMessage {
            get {
                return ResourceManager.GetString("Forms_Settings_HeaderImageCacheMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Forms_Settings_Language {
            get {
                return ResourceManager.GetString("Forms_Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move files synchronously if bigger than.
        /// </summary>
        internal static string Forms_Settings_MoveFilesSyncBySize {
            get {
                return ResourceManager.GetString("Forms_Settings_MoveFilesSyncBySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Logs Folder.
        /// </summary>
        internal static string Forms_Settings_OpenLogsFolder {
            get {
                return ResourceManager.GetString("Forms_Settings_OpenLogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a sound on completion.
        /// </summary>
        internal static string Forms_Settings_PlayASoundOnCompletion {
            get {
                return ResourceManager.GetString("Forms_Settings_PlayASoundOnCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Forms_Settings_Remove {
            get {
                return ResourceManager.GetString("Forms_Settings_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove files at Source directory.
        /// </summary>
        internal static string Forms_Settings_RemoveFiles {
            get {
                return ResourceManager.GetString("Forms_Settings_RemoveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report File Movement.
        /// </summary>
        internal static string Forms_Settings_ReportFileMovement {
            get {
                return ResourceManager.GetString("Forms_Settings_ReportFileMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep searching on library change.
        /// </summary>
        internal static string Forms_Settings_SearchOnLibraryChange {
            get {
                return ResourceManager.GetString("Forms_Settings_SearchOnLibraryChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation method for games.
        /// </summary>
        internal static string Forms_Settings_SizeCalculationMethod {
            get {
                return ResourceManager.GetString("Forms_Settings_SizeCalculationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort games by.
        /// </summary>
        internal static string Forms_Settings_SortGamesBy {
            get {
                return ResourceManager.GetString("Forms_Settings_SortGamesBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Task Manager on Startup.
        /// </summary>
        internal static string Forms_Settings_StartTaskManagerOnStartup {
            get {
                return ResourceManager.GetString("Forms_Settings_StartTaskManagerOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabItem Text Color.
        /// </summary>
        internal static string Forms_Settings_TabItemTextColor {
            get {
                return ResourceManager.GetString("Forms_Settings_TabItemTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Manager Default Settings.
        /// </summary>
        internal static string Forms_Settings_TaskManagerDefaults {
            get {
                return ResourceManager.GetString("Forms_Settings_TaskManagerDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color:.
        /// </summary>
        internal static string Forms_Settings_TextColor {
            get {
                return ResourceManager.GetString("Forms_Settings_TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Accent.
        /// </summary>
        internal static string Forms_Settings_ThemeAccent {
            get {
                return ResourceManager.GetString("Forms_Settings_ThemeAccent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Base.
        /// </summary>
        internal static string Forms_Settings_ThemeBase {
            get {
                return ResourceManager.GetString("Forms_Settings_ThemeBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransparentWhite.
        /// </summary>
        internal static string Forms_Settings_TransparentWhite {
            get {
                return ResourceManager.GetString("Forms_Settings_TransparentWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window BG.
        /// </summary>
        internal static string Forms_Settings_WindowBG {
            get {
                return ResourceManager.GetString("Forms_Settings_WindowBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLM.
        /// </summary>
        internal static string Forms_SLM {
            get {
                return ResourceManager.GetString("Forms_SLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.
        /// </summary>
        internal static string Forms_Steam {
            get {
                return ResourceManager.GetString("Forms_Steam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Install.
        /// </summary>
        internal static string Forms_TaskManager_AutoInstall {
            get {
                return ResourceManager.GetString("Forms_TaskManager_AutoInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Backup Updates.
        /// </summary>
        internal static string Forms_TaskManager_CheckForBackupUpdates {
            get {
                return ResourceManager.GetString("Forms_TaskManager_CheckForBackupUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Completed Tasks.
        /// </summary>
        internal static string Forms_TaskManager_ClearCompletedTasks {
            get {
                return ResourceManager.GetString("Forms_TaskManager_ClearCompletedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETED.
        /// </summary>
        internal static string Forms_TaskManager_Completed {
            get {
                return ResourceManager.GetString("Forms_TaskManager_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress.
        /// </summary>
        internal static string Forms_TaskManager_Compress {
            get {
                return ResourceManager.GetString("Forms_TaskManager_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Forms_TaskManager_Delete {
            get {
                return ResourceManager.GetString("Forms_TaskManager_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Forms_TaskManager_Pause {
            get {
                return ResourceManager.GetString("Forms_TaskManager_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        internal static string Forms_TaskManager_ProgressBarPerc {
            get {
                return ResourceManager.GetString("Forms_TaskManager_ProgressBarPerc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Original Files.
        /// </summary>
        internal static string Forms_TaskManager_RemoveFiles {
            get {
                return ResourceManager.GetString("Forms_TaskManager_RemoveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected Game(s) from Queue.
        /// </summary>
        internal static string Forms_TaskManager_RemoveFromQueue {
            get {
                return ResourceManager.GetString("Forms_TaskManager_RemoveFromQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report File Movement.
        /// </summary>
        internal static string Forms_TaskManager_ReportFileMovement {
            get {
                return ResourceManager.GetString("Forms_TaskManager_ReportFileMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Forms_TaskManager_Start {
            get {
                return ResourceManager.GetString("Forms_TaskManager_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Forms_TaskManager_Stop {
            get {
                return ResourceManager.GetString("Forms_TaskManager_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target: {0}.
        /// </summary>
        internal static string Forms_TaskManager_TargetLibrary {
            get {
                return ResourceManager.GetString("Forms_TaskManager_TargetLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Library Manager.
        /// </summary>
        internal static string MoveGamesConfirmError {
            get {
                return ResourceManager.GetString("MoveGamesConfirmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function is not implemented, process cancelled.
        /// </summary>
        internal static string MoveGamesConfirmErrorMessage {
            get {
                return ResourceManager.GetString("MoveGamesConfirmErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Library Manager.
        /// </summary>
        internal static string MoveGamesInLibrary {
            get {
                return ResourceManager.GetString("MoveGamesInLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move games in Library before deleting the library?.
        /// </summary>
        internal static string MoveGamesInLibraryMessage {
            get {
                return ResourceManager.GetString("MoveGamesInLibraryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap no_image_available {
            get {
                object obj = ResourceManager.GetObject("no_image_available", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin directory does not exists.
        ///
        ///{NotFoundDirectoryFullPath}.
        /// </summary>
        internal static string Origin_DirectoryNotExists {
            get {
                return ResourceManager.GetString("Origin_DirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin config file doesn&apos;t contains &apos;DownloadInPlaceDir&apos; config
        ///
        ///{OriginConfigFilePath}.
        /// </summary>
        internal static string Origin_MissingKey {
            get {
                return ResourceManager.GetString("Origin_MissingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete files (using SLM).
        /// </summary>
        internal static string OriginApp_CMenu_DeleteFilesSLM {
            get {
                return ResourceManager.GetString("OriginApp_CMenu_DeleteFilesSLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete files (using TaskManager).
        /// </summary>
        internal static string OriginApp_CMenu_DeleteFilesTM {
            get {
                return ResourceManager.GetString("OriginApp_CMenu_DeleteFilesTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {AppName} ({SizeOnDisk}).
        /// </summary>
        internal static string OriginApp_CMenu_DiskInfo {
            get {
                return ResourceManager.GetString("OriginApp_CMenu_DiskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string OriginApp_CMenu_Install {
            get {
                return ResourceManager.GetString("OriginApp_CMenu_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        internal static string OriginApp_CMenu_Repair {
            get {
                return ResourceManager.GetString("OriginApp_CMenu_Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run (Unavailable).
        /// </summary>
        internal static string OriginApp_CMenu_Run {
            get {
                return ResourceManager.GetString("OriginApp_CMenu_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while parsing context menu, most likely happened duo typo on color name.
        ///
        ///{ExceptionMessage}.
        /// </summary>
        internal static string OriginAppInfo_FormatException {
            get {
                return ResourceManager.GetString("OriginAppInfo_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin game installation directory is not exists?!.
        /// </summary>
        internal static string OriginDirectoryNotExists {
            get {
                return ResourceManager.GetString("OriginDirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin App Installation.
        /// </summary>
        internal static string OriginInstallation {
            get {
                return ResourceManager.GetString("OriginInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin game installation completed.
        ///
        ///Installer result message:
        ///{installerResult}.
        /// </summary>
        internal static string OriginInstallation_Completed {
            get {
                return ResourceManager.GetString("OriginInstallation_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asking Origin to install {AppName} as you have requested.
        ///
        ///Waiting for Origin to complete the installation....
        /// </summary>
        internal static string OriginInstallation_Ongoing {
            get {
                return ResourceManager.GetString("OriginInstallation_Ongoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asking Origin to install {AppName} as you have requested..
        /// </summary>
        internal static string OriginInstallation_Start {
            get {
                return ResourceManager.GetString("OriginInstallation_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open library in explorer ({LibraryFullPath}).
        /// </summary>
        internal static string OriginLibrary_CMenu_Open {
            get {
                return ResourceManager.GetString("OriginLibrary_CMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from SLM.
        /// </summary>
        internal static string OriginLibrary_CMenu_RemoveFromSLM {
            get {
                return ResourceManager.GetString("OriginLibrary_CMenu_RemoveFromSLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Manifest Version from Origin game: {OriginApp} - {ManifestVersion}.
        /// </summary>
        internal static string OriginUnknownManifestFile {
            get {
                return ResourceManager.GetString("OriginUnknownManifestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{AppName}] PathTooLongException happened while copying files. Nothing can be made by SLM in this error.
        ///
        ///Error: {ExceptionMessage}
        ///
        ///Would you like to remove files that already moved from target library?.
        /// </summary>
        internal static string PathTooLongException {
            get {
                return ResourceManager.GetString("PathTooLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{AppName}] Populating file list, please wait.
        /// </summary>
        internal static string PopulatingFileList {
            get {
                return ResourceManager.GetString("PopulatingFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t delete the archive file.
        /// </summary>
        internal static string ReadZip_DontDelete {
            get {
                return ResourceManager.GetString("ReadZip_DontDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while parsing zip file.
        /// </summary>
        internal static string ReadZip_InvalidDataException {
            get {
                return ResourceManager.GetString("ReadZip_InvalidDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while parsing zip file:
        ///
        ///{ZipPath}
        ///
        ///It is still suggested to check the archive file manually to see if it is really corrupted or not!
        ///
        ///Would you like to remove the given archive file?.
        /// </summary>
        internal static string ReadZip_InvalidDataExceptionMessage {
            get {
                return ResourceManager.GetString("ReadZip_InvalidDataExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while parsing zip file.
        /// </summary>
        internal static string ReadZip_IOException {
            get {
                return ResourceManager.GetString("ReadZip_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while parsing zip file:
        ///
        ///{ZipPath}
        ///
        ///It is still suggested to check the archive file manually to see if it is really corrupted or not!
        ///
        ///Would you like to remove the given archive file?.
        /// </summary>
        internal static string ReadZip_IOExceptionMessage {
            get {
                return ResourceManager.GetString("ReadZip_IOExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove moved files?.
        /// </summary>
        internal static string RemoveMovedFiles {
            get {
                return ResourceManager.GetString("RemoveMovedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for backup updates as you have requested..
        /// </summary>
        internal static string Steam_CheckForBackupUpdates {
            get {
                return ResourceManager.GetString("Steam_CheckForBackupUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{CurrentTime}] Check for Backup updates completed..
        /// </summary>
        internal static string Steam_CheckForBackupUpdates_Completed {
            get {
                return ResourceManager.GetString("Steam_CheckForBackupUpdates_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for:
        ///
        ///{CurrentAppName}.
        /// </summary>
        internal static string Steam_CheckForBackupUpdates_Progress {
            get {
                return ResourceManager.GetString("Steam_CheckForBackupUpdates_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{CurrentTime}] An update is available for: {CurrentAppName} - Old backup time: {CurrentAppLastUpdatedOn} - Updated on: {NewAppLastUpdatedOn} - Target: {CurrentAppSteamFullPath} - Source: {NewAppSteamFullPath}.
        /// </summary>
        internal static string Steam_CheckForBackupUpdates_UpdateFound {
            get {
                return ResourceManager.GetString("Steam_CheckForBackupUpdates_UpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam needs to be closed.
        /// </summary>
        internal static string Steam_NeedsToBeClosed {
            get {
                return ResourceManager.GetString("Steam_NeedsToBeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.exe could not found and user doesn&apos;t wants to terminate the process..
        /// </summary>
        internal static string Steam_NeedsToBeClosed_NotFoundAndUserCancelled {
            get {
                return ResourceManager.GetString("Steam_NeedsToBeClosed_NotFoundAndUserCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t wants to close Steam, can not continue to process..
        /// </summary>
        internal static string Steam_NeedsToBeClosed_UserCancelled {
            get {
                return ResourceManager.GetString("Steam_NeedsToBeClosed_UserCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam needs to be closed for this action. Would you like SLM to close Steam?.
        /// </summary>
        internal static string Steam_NeedsToBeClosedMessage {
            get {
                return ResourceManager.GetString("Steam_NeedsToBeClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.exe could not found (even it is already working?), SLM can try to terminate the Steam processes now if you want to.
        ///
        ///Active Steam process path: {ActiveSteamPath}.
        /// </summary>
        internal static string Steam_NeedsToBeClosedMessage2 {
            get {
                return ResourceManager.GetString("Steam_NeedsToBeClosedMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam installation couldn&apos;t be found.
        /// </summary>
        internal static string Steam_NotInstalled {
            get {
                return ResourceManager.GetString("Steam_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam couldn&apos;t be found under registry. Would you like to locate Steam manually?.
        /// </summary>
        internal static string Steam_NotInstalledMessage {
            get {
                return ResourceManager.GetString("Steam_NotInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Steam?.
        /// </summary>
        internal static string Steam_Start {
            get {
                return ResourceManager.GetString("Steam_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t wants to start Steam..
        /// </summary>
        internal static string Steam_Start_UserCancelled {
            get {
                return ResourceManager.GetString("Steam_Start_UserCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like SLM to Start Steam?.
        /// </summary>
        internal static string Steam_StartMessage {
            get {
                return ResourceManager.GetString("Steam_StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (De)Compress.
        /// </summary>
        internal static string SteamApp_CMenu_Compress {
            get {
                return ResourceManager.GetString("SteamApp_CMenu_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete files (using SLM).
        /// </summary>
        internal static string SteamApp_CMenu_DeleteFilesSLM {
            get {
                return ResourceManager.GetString("SteamApp_CMenu_DeleteFilesSLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete files (using TaskManager).
        /// </summary>
        internal static string SteamApp_CMenu_DeleteFilesTM {
            get {
                return ResourceManager.GetString("SteamApp_CMenu_DeleteFilesTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {AppName} ({SizeOnDisk}).
        /// </summary>
        internal static string SteamApp_CMenu_DiskInfo {
            get {
                return ResourceManager.GetString("SteamApp_CMenu_DiskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Hub.
        /// </summary>
        internal static string SteamApp_CMenu_GameHub {
            get {
                return ResourceManager.GetString("SteamApp_CMenu_GameHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string SteamApp_CMenu_Play {
            get {
                return ResourceManager.GetString("SteamApp_CMenu_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed Workshop Items.
        /// </summary>
        internal static string SteamApp_CMenu_SubscribedWorkshopItems {
            get {
                return ResourceManager.GetString("SteamApp_CMenu_SubscribedWorkshopItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View ACF File.
        /// </summary>
        internal static string SteamApp_CMenu_ViewACF {
            get {
                return ResourceManager.GetString("SteamApp_CMenu_ViewACF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        internal static string SteamApp_CMenu_Workshop {
            get {
                return ResourceManager.GetString("SteamApp_CMenu_Workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while populating files at common directory for game: {AppName} - Directory:
        ///{CommonFolderFullPath}
        ///
        ///Error:
        ///{ExceptionMessage}.
        /// </summary>
        internal static string SteamApp_GetCommonFilesError {
            get {
                return ResourceManager.GetString("SteamApp_GetCommonFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Library Manager.
        /// </summary>
        internal static string SteamApp_RemovingError {
            get {
                return ResourceManager.GetString("SteamApp_RemovingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error happened while removing app files. {FullPath}.
        /// </summary>
        internal static string SteamApp_RemovingErrorMessage {
            get {
                return ResourceManager.GetString("SteamApp_RemovingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ArchiveFullPath} is in use. Delaying the task until archive gets free..
        /// </summary>
        internal static string SteamAppInfo_CompressedArchiveExistsAndInUse {
            get {
                return ResourceManager.GetString("SteamAppInfo_CompressedArchiveExistsAndInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{AppName}] File compressed: {FileNameInArchive}.
        /// </summary>
        internal static string SteamAppInfo_FileCompressed {
            get {
                return ResourceManager.GetString("SteamAppInfo_FileCompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{AppName}] File decompressed: {NewFileFullPath}.
        /// </summary>
        internal static string SteamAppInfo_FileDecompressed {
            get {
                return ResourceManager.GetString("SteamAppInfo_FileDecompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while parsing context menu, most likely happened duo typo on color name.
        ///
        ///{ExceptionMessage}.
        /// </summary>
        internal static string SteamAppInfo_FormatException {
            get {
                return ResourceManager.GetString("SteamAppInfo_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create steam library folder at: {SteamAppsFolderFullPath}
        ///
        ///Try running SLM as administrator..
        /// </summary>
        internal static string SteamLibrary_CantCreate {
            get {
                return ResourceManager.GetString("SteamLibrary_CantCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete games in library.
        /// </summary>
        internal static string SteamLibrary_CMenu_DeleteGames {
            get {
                return ResourceManager.GetString("SteamLibrary_CMenu_DeleteGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open library in explorer ({LibraryFullPath}).
        /// </summary>
        internal static string SteamLibrary_CMenu_Open {
            get {
                return ResourceManager.GetString("SteamLibrary_CMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from SLM.
        /// </summary>
        internal static string SteamLibrary_CMenu_RemoveFromSLM {
            get {
                return ResourceManager.GetString("SteamLibrary_CMenu_RemoveFromSLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove library from Steam (/w files).
        /// </summary>
        internal static string SteamLibrary_CMenu_RemoveFromSteam {
            get {
                return ResourceManager.GetString("SteamLibrary_CMenu_RemoveFromSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Library Manager.
        /// </summary>
        internal static string SteamLibraryManager {
            get {
                return ResourceManager.GetString("SteamLibraryManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{AppName}] Operation cancelled by user. Time Elapsed: {ElapsedTime}.
        /// </summary>
        internal static string TaskCancelled_ElapsedTime {
            get {
                return ResourceManager.GetString("TaskCancelled_ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{AppName}] Game movement cancelled. Would you like to remove files that already moved from target library?.
        /// </summary>
        internal static string TaskCancelled_RemoveFiles {
            get {
                return ResourceManager.GetString("TaskCancelled_RemoveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{AppName}] Time elapsed: {ElapsedTime} - Average speed: {AverageSpeed} MB/sec - Average file size: {AverageFileSize}.
        /// </summary>
        internal static string TaskCompleted {
            get {
                return ResourceManager.GetString("TaskCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{CurrentTime}] [TaskManager] Task Manager is now active and waiting for tasks....
        /// </summary>
        internal static string TaskManager_Active {
            get {
                return ResourceManager.GetString("TaskManager_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Library Manager.
        /// </summary>
        internal static string TaskManager_AlreadyTasked {
            get {
                return ResourceManager.GetString("TaskManager_AlreadyTasked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is already tasked.
        ///
        ///Game: {AppName}
        ///Target Library: {LibraryFullPath}.
        /// </summary>
        internal static string TaskManager_AlreadyTaskedMessage {
            get {
                return ResourceManager.GetString("TaskManager_AlreadyTaskedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{CurrentTime}] [TaskManager] Task Manager is paused as requested..
        /// </summary>
        internal static string TaskManager_Paused {
            get {
                return ResourceManager.GetString("TaskManager_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{CurrentTime}] [{AppName}] Removing copied source files as requested. This may take a while, please wait..
        /// </summary>
        internal static string TaskManager_RemoveOldFiles {
            get {
                return ResourceManager.GetString("TaskManager_RemoveOldFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{CurrentTime}] [{AppName}] Files removed, task is completed now..
        /// </summary>
        internal static string TaskManager_RemoveOldFilesCompleted {
            get {
                return ResourceManager.GetString("TaskManager_RemoveOldFilesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{CurrentTime}] [TaskManager] Task Manager is stopped..
        /// </summary>
        internal static string TaskManager_Stopped {
            get {
                return ResourceManager.GetString("TaskManager_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Clear Completed Tasks.
        /// </summary>
        internal static string TaskManagerView_AutoClearCompletedTasks {
            get {
                return ResourceManager.GetString("TaskManagerView_AutoClearCompletedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Scroll Logs.
        /// </summary>
        internal static string TaskManagerView_AutoScrollLogs {
            get {
                return ResourceManager.GetString("TaskManagerView_AutoScrollLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string TaskStatus_Completed {
            get {
                return ResourceManager.GetString("TaskStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing: {CurrentFileName} ({FileSize}).
        /// </summary>
        internal static string TaskStatus_CompressingFile {
            get {
                return ResourceManager.GetString("TaskStatus_CompressingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying file: {Percentage}%.
        /// </summary>
        internal static string TaskStatus_CopyingFile {
            get {
                return ResourceManager.GetString("TaskStatus_CopyingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompressing: {NewFileName} ({NewFileSize}).
        /// </summary>
        internal static string TaskStatus_Decompress {
            get {
                return ResourceManager.GetString("TaskStatus_Decompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting directory: {DirectoryName}.
        /// </summary>
        internal static string TaskStatus_DeletingDirectory {
            get {
                return ResourceManager.GetString("TaskStatus_DeletingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting: {FileName} ({FormattedFileSize}).
        /// </summary>
        internal static string TaskStatus_DeletingFile {
            get {
                return ResourceManager.GetString("TaskStatus_DeletingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Library Manager.
        /// </summary>
        internal static string TM_TaskActiveError {
            get {
                return ResourceManager.GetString("TM_TaskActiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{AppName}] You can&apos;t remove an app from Task Manager which is currently being moved.
        ///
        ///Please Stop the Task Manager first..
        /// </summary>
        internal static string TM_TaskActiveErrorMessage {
            get {
                return ResourceManager.GetString("TM_TaskActiveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnauthorizedAccessException.
        /// </summary>
        internal static string UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{FullPath}] An error related to folder permissions happened during generating library content. Running SLM as Administrator might help.
        ///
        ///Error: {ExceptionMessage}.
        /// </summary>
        internal static string UnauthorizedAccessExceptionMessage {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using the latest version of SLM..
        /// </summary>
        internal static string Updater_LatestVersionMessage {
            get {
                return ResourceManager.GetString("Updater_LatestVersionMessage", resourceCulture);
            }
        }
    }
}
