//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam_Library_Manager.Languages.Forms.Games {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rightClickMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rightClickMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Steam_Library_Manager.Languages.Forms.Games.rightClickMenu", typeof(rightClickMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyunlar.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam üzerinden yedekle.
        /// </summary>
        public static string menuItem_backupUsingSteam {
            get {
                return ResourceManager.GetString("menuItem_backupUsingSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistem gereksinimlerini kontrol et.
        /// </summary>
        public static string menuItem_checkSysRequirements {
            get {
                return ResourceManager.GetString("menuItem_checkSysRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyunun dosyalarını birleştir (defrag).
        /// </summary>
        public static string menuItem_defrag {
            get {
                return ResourceManager.GetString("menuItem_defrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (ID: {1}).
        /// </summary>
        public static string menuItem_gameNameWithAppID {
            get {
                return ResourceManager.GetString("menuItem_gameNameWithAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk üzerindeki boyutu: {0}.
        /// </summary>
        public static string menuItem_gameSizeOnDisk {
            get {
                return ResourceManager.GetString("menuItem_gameSizeOnDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACF dosyasını aç.
        /// </summary>
        public static string menuItem_openAcfFile {
            get {
                return ResourceManager.GetString("menuItem_openAcfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyna.
        /// </summary>
        public static string menuItem_play {
            get {
                return ResourceManager.GetString("menuItem_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string menuItem_uninstall {
            get {
                return ResourceManager.GetString("menuItem_uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLM ile sil.
        /// </summary>
        public static string menuItem_uninstallWithSLM {
            get {
                return ResourceManager.GetString("menuItem_uninstallWithSLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyunun içerik dosyalarını doğrula.
        /// </summary>
        public static string menuItem_validateGameFiles {
            get {
                return ResourceManager.GetString("menuItem_validateGameFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya gezgininde görüntüle.
        /// </summary>
        public static string menuItem_viewOnDisk {
            get {
                return ResourceManager.GetString("menuItem_viewOnDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağazada görüntüle.
        /// </summary>
        public static string menuItem_viewOnStore {
            get {
                return ResourceManager.GetString("menuItem_viewOnStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam istemcisi ile mağazada görüntüle.
        /// </summary>
        public static string menuItem_viewOnStoreWithSteam {
            get {
                return ResourceManager.GetString("menuItem_viewOnStoreWithSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adlı oyunun tüm dosyaları istendiği üzere silindi..
        /// </summary>
        public static string message_appRemovedAsRequested {
            get {
                return ResourceManager.GetString("message_appRemovedAsRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adlı oyunu silmek istediğinize emin misiniz?{1}{1}BU İŞLEM GERİ ALINAMAZ!.
        /// </summary>
        public static string message_sureToRemoveGame {
            get {
                return ResourceManager.GetString("message_sureToRemoveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu işlemi yapmak istediğinize emin misiniz?.
        /// </summary>
        public static string messageTitle_sureToRemoveGame {
            get {
                return ResourceManager.GetString("messageTitle_sureToRemoveGame", resourceCulture);
            }
        }
    }
}
