//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam_Library_Manager.Languages.Forms.Libraries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rightClickMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rightClickMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Steam_Library_Manager.Languages.Forms.Libraries.rightClickMenu", typeof(rightClickMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries.
        /// </summary>
        public static string Libraries {
            get {
                return ResourceManager.GetString("Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete games in library.
        /// </summary>
        public static string menuItem_deleteGamesInLibrary {
            get {
                return ResourceManager.GetString("menuItem_deleteGamesInLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete library.
        /// </summary>
        public static string menuItem_deleteLibrary {
            get {
                return ResourceManager.GetString("menuItem_deleteLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move library.
        /// </summary>
        public static string menuItem_moveLibrary {
            get {
                return ResourceManager.GetString("menuItem_moveLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open library in file explorer.
        /// </summary>
        public static string menuItem_openLibraryInExplorer {
            get {
                return ResourceManager.GetString("menuItem_openLibraryInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh games in library.
        /// </summary>
        public static string menuItem_refreshGameList {
            get {
                return ResourceManager.GetString("menuItem_refreshGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from list.
        /// </summary>
        public static string menuITem_removeBackupLibraryFromList {
            get {
                return ResourceManager.GetString("menuITem_removeBackupLibraryFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!{1}All games in Library ({0}) deleted..
        /// </summary>
        public static string message_allGamesSuccesfullyDeleted {
            get {
                return ResourceManager.GetString("message_allGamesSuccesfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move games in library before deleting?.
        /// </summary>
        public static string message_moveGamesInLibraryBeforeDelete {
            get {
                return ResourceManager.GetString("message_moveGamesInLibraryBeforeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while removing games from library {0}.
        /// </summary>
        public static string message_unknownErrorWhileDeletingGames {
            get {
                return ResourceManager.GetString("message_unknownErrorWhileDeletingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move games.
        /// </summary>
        public static string messageTitle_moveGamesInLibraryBeforeDelete {
            get {
                return ResourceManager.GetString("messageTitle_moveGamesInLibraryBeforeDelete", resourceCulture);
            }
        }
    }
}
